title: kuntaulab
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2930946038104594
  brandStrength: 0.1424630128312856
  lightness: 0.6386773958802223
  brandColors:
    - '#B4AF91'
    - '#787746'
    - '#40411E'
    - '#32331D'
    - '#C03000'
  rhythmicContrast: 0.6032083802856505
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: kuntaulab
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7353129787370563
layout_spectrum: 0.40347487246617675
