name: kuntaulab
favicon: null
layout_spectrum: 0.6341336031910032
typography_spectrum: 0.5161706728395075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9512739893980324
  lightness: 0.5805241724010557
  saturation: 0.11870124842971563
  rhythmicContrast: 0.13262035767547786
purpose: []
