typography_spectrum: 0.30561
color:
  brandColors:
    - '#FFFFFF'
    - '#BCBCBC'
    - '#424242'
    - '#FE9900'
    - '#808080'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75296
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Annie Beldia
  email: annie.beldia@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/840e1ad7-396a-466f-ad87-b39e66edf0a1.png
name: kuntaulab
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8ad97d50-7d5f-464a-b663-d8483e200250.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: kuntaulab
purpose: []
