name: kuntaulab
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53333
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: kuntaulab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#BCBCBC'
    - '#424242'
    - '#FE9900'
    - '#808080'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
