favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5340502
  brandStrength: 0.9512739893980324
  rhythmicContrast: 0.4121864
  brandColors:
    - '#FFFFFF'
    - '#BCBCBC'
    - '#424242'
    - '#FE9900'
    - '#808080'
  lightness: 0.3387097
typography_spectrum: 0.4659498
layout_spectrum: 0.4569893
analytics:
  twitter: null
  google: null
  facebook: null
name: kuntaulab
